/*VERSION DE WINDOWS CRUDS COMPLETOS*/


package vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedrohdez
 */
public class PantallaConsultarRecepcionista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaRecepcionista
     */
    Connection con;
    String linkbd = "jdbc:mysql://localhost:3306/VISTA?useTimezone=true&serverTimezone=UTC";
    
    public PantallaConsultarRecepcionista() {
        initComponents();
        setSize(1000,800);
        setLocation(0,-25);
        
    }
    
    public void borraTabla(){
        DefaultTableModel modelo = (DefaultTableModel)TbRecepcionistas.getModel();
        modelo.setRowCount(0);
    }
    
    public void IniciarVentana(){
        CbTodo.setSelected(false);
        CbBuscar.setSelected(true);
        LblNombre.setVisible(true);
        LblApellido.setVisible(true);
        BConsultar.setVisible(true);
        tfNombre.setVisible(true);
        tfNombre.setText("");
        tfApellido.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        LblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbRecepcionistas = new javax.swing.JTable();
        BConsultar = new javax.swing.JButton();
        LblApellido = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        CbTodo = new javax.swing.JCheckBox();
        CbBuscar = new javax.swing.JCheckBox();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consulta de recepcionistas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 0, -1, -1));
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 48, 199, -1));

        LblNombre.setText("Nombre:");
        getContentPane().add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));

        TbRecepcionistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(TbRecepcionistas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, 380, 123));

        BConsultar.setText("Consultar");
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(BConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 124, -1, -1));

        LblApellido.setText("Apellido:");
        getContentPane().add(LblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, 34));
        getContentPane().add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 92, 198, -1));

        CbTodo.setText("Mostrar todo");
        CbTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTodoActionPerformed(evt);
            }
        });
        getContentPane().add(CbTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 25, -1, -1));

        CbBuscar.setText("Buscar");
        CbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(CbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 25, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
      
        borraTabla();
        
        if(tfNombre.getText().equals("") && tfApellido.getText().equals("") ){
           JOptionPane.showMessageDialog(null, "Error. Rellene los dos campos e inténtelo de nuevo.");
        }
        
        else{
            try {
      
                DefaultTableModel modelo = (DefaultTableModel)TbRecepcionistas.getModel();

                con = DriverManager.getConnection(linkbd, "root", "");
                Statement stmt = con.createStatement();
                ResultSet rs;
                
                if(tfNombre.getText().equals("")){
                    rs = stmt.executeQuery("SELECT * FROM Recepcionistas WHERE Apellido = '"+tfApellido.getText()+"'");
                }
                else if(tfApellido.getText().equals("")){
                    rs = stmt.executeQuery("SELECT * FROM Recepcionistas WHERE Nombre = '"+tfNombre.getText()+"'");
                }
                else{
                    rs = stmt.executeQuery("SELECT * FROM Recepcionistas WHERE Apellido = '"+tfApellido.getText()+"' AND Nombre = '"+tfNombre.getText()+"'");
                }

                rs.first();

                do{
                    String[] fila = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                    modelo.addRow(fila);
                }while(rs.next());

            } 
            catch (SQLException ex) {
                Logger.getLogger(PantallaConsultarRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "El/La recepcionista no existe. Inténtelo de nuevo.");
            }
        }    
        
    }//GEN-LAST:event_BConsultarActionPerformed

    private void CbTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTodoActionPerformed
        borraTabla();
        CbBuscar.setSelected(false);
        LblNombre.setVisible(false);
        LblApellido.setVisible(false);
        tfNombre.setVisible(false);
        tfNombre.setText("");
        tfApellido.setVisible(false);
        tfApellido.setText("");
        BConsultar.setVisible(false);
        try {  
             DefaultTableModel modelo = (DefaultTableModel)TbRecepcionistas.getModel();
            
            con = DriverManager.getConnection(linkbd, "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM Recepcionistas");
            
            rs.first();
            
            do{
                String[] fila = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)};
                modelo.addRow(fila);
            }while(rs.next());
                    
        } catch (SQLException ex) {
            Logger.getLogger(PantallaConsultarRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
        }
    }//GEN-LAST:event_CbTodoActionPerformed

    private void CbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbBuscarActionPerformed

        CbTodo.setSelected(false);
        LblNombre.setVisible(true);
        LblApellido.setVisible(true);
        tfNombre.setVisible(true);
        tfApellido.setVisible(true);
        BConsultar.setVisible(true);
    }//GEN-LAST:event_CbBuscarActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        MainWindow.startTime = System.currentTimeMillis();
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConsultar;
    private javax.swing.JCheckBox CbBuscar;
    private javax.swing.JCheckBox CbTodo;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JTable TbRecepcionistas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
