/*VERSION DE WINDOWS CRUDS COMPLETOS*/


package vista;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author pedrohdez
 */


public class PantallaActualizarRecepcionista extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaActualizarRecepcionista
     */
    Connection con;
    boolean exito = true;
    String linkbd = "jdbc:mysql://localhost:3306/VISTA?useTimezone=true&serverTimezone=UTC";
    
    public PantallaActualizarRecepcionista() {
        setSize(1000,800);
        setLocation(0,-25);
        initComponents();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
                    } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaActualizarRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void IniciarVentana(){
        tfNombre.setText("");
        tfUsuario.setText("");
        tfUsuario2.setText("");
        tfApellido.setText("");
        tfContraseña.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitulo = new javax.swing.JLabel();
        LblRecep = new javax.swing.JLabel();
        LblInfo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        tfUsuario2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfUsuario = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JTextField();
        BActualizar = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        LblTitulo.setText("Actualizar información de recepcionistas");

        LblRecep.setText("Recepcionista a actualizar");

        LblInfo.setText("Información a actualizar");

        LblNombre.setText("Nombre de usuario:");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        BActualizar.setText("Actualizar Información");
        BActualizar.setToolTipText("");
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LblRecep))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblNombre)
                        .addGap(3, 3, 3)
                        .addComponent(tfUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LblInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfContraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(LblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(BActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRecep)
                    .addComponent(LblInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LblNombre)
                            .addComponent(tfUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BActualizar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
       
        
        if(tfUsuario2.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Error. Por favor rellene el Campo: 'Nombre de usuario'.");
        }
        else{
            try {
                con = DriverManager.getConnection(linkbd, "root", "");    
                Statement stmt = con.createStatement();
                    
                if(tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Contrasena = '"+tfContraseña.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Usuario = '"+tfUsuario.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Usuario = '"+tfUsuario.getText()+"', Contrasena = '"+tfContraseña.getText()+
                                       "' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Apellido = '"+tfApellido.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Apellido = '"+tfApellido.getText()+"', Contrasena = '"+tfContraseña.getText()+
                                       "' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Apellido = '"+tfApellido.getText()+"', Usuario = '"+tfUsuario.getText()+
                                       "' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Contrasena = '"+tfContraseña.getText()+"', Apellido = '"+tfApellido.getText()+
                                       "', Usuario = '"+tfUsuario.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(!tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Nombre = '"+tfNombre.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(!tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Nombre = '"+tfNombre.getText()+"', Contrasena = '"+tfContraseña.getText()+
                                       "' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(!tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Nombre = '"+tfNombre.getText()+"', Usuario = '"+tfUsuario.getText()+
                                       "' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(!tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Nombre = '"+tfNombre.getText()+"', Usuario = '"+tfUsuario.getText()+
                                       "', Contrasena = '"+tfContraseña.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
               if(!tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Nombre = '"+tfNombre.getText()+"', Apellido = '"+tfApellido.getText()+
                                       "' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(!tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Nombre = '"+tfNombre.getText()+"', Apellido = '"+tfApellido.getText()+
                                       "', Contrasena = '"+tfContraseña.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(!tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Apellido = '"+tfApellido.getText()+"', Usuario = '"+tfUsuario.getText()+
                                       "', Nombre = '"+tfNombre.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(!tfNombre.getText().isEmpty() && !tfApellido.getText().isEmpty() && !tfUsuario.getText().isEmpty() && !tfContraseña.getText().isEmpty()){
                    stmt.executeUpdate("UPDATE Recepcionistas SET Nombre = '"+tfNombre.getText()+"', Apellido = '"+tfApellido.getText()+"', Usuario = '"+tfUsuario.getText()+
                                       "', Contrasena = '"+tfContraseña.getText()+"' WHERE Usuario = '"+tfUsuario2.getText()+"'");
                    exito = true;
                }
                if(tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Por favor, rellene el formulario.");
                    exito = false;
                }
                
                if(stmt.getUpdateCount() == 0 && !(tfNombre.getText().isEmpty() && tfApellido.getText().isEmpty() && 
                   tfUsuario.getText().isEmpty() && tfContraseña.getText().isEmpty())){
                    JOptionPane.showMessageDialog(null, "Error. El recepcionista no existe. Intente de nuevo.");
                    exito = false;
                }
                if(exito){
                    JOptionPane.showMessageDialog(null, "Se han actualizado correctamente los datos");
                    tfApellido.setText("");
                    tfContraseña.setText("");
                    tfNombre.setText("");
                    tfUsuario.setText("");
                }
                
            } 
            catch (SQLException ex) {
                Logger.getLogger(PantallaActualizarRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error. Intente de nuevo.");
            }
            
        }
       
    }//GEN-LAST:event_BActualizarActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        MainWindow.startTime = System.currentTimeMillis();
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JLabel LblInfo;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblRecep;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfUsuario;
    private javax.swing.JTextField tfUsuario2;
    // End of variables declaration//GEN-END:variables
}
