/*VERSION DE WINDOWS CRUDS COMPLETOS*/

package vista;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class PantallaRegistrarRecepcionista extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaRegistrarRecepcionista
     */
    
    Connection con;
    String linkbd = "jdbc:mysql://localhost:3306/VISTA?useTimezone=true&serverTimezone=UTC";
    boolean errorFormulario, errorUsuario;
    
    public PantallaRegistrarRecepcionista() {
        initComponents();
        setSize(1000,800);
        setLocation(0,-25);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaRegistrarRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void IniciarVentana(){
        tfNombre.setText("");
        tfApellido.setText("");
        tfNombreUsuario.setText("");
        tfContraseña.setText("");
        errorFormulario = errorUsuario = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfNombreUsuario = new javax.swing.JTextField();
        tfContraseña = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de recepcionistas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 0, -1, -1));
        getContentPane().add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 182, -1));
        getContentPane().add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 182, -1));
        getContentPane().add(tfNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 182, -1));
        getContentPane().add(tfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 182, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 122, 42));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 47, -1, -1));

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 76, -1, -1));

        jLabel4.setText("Usuario: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(tfNombre.getText().equals("") || tfApellido.getText().equals("") ||
           tfContraseña.getText().equals("") || tfNombreUsuario.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Error. Rellene el formulario completo e inténtelo de nuevo.");
            errorFormulario = true;
       }
       
       if(!tfNombreUsuario.getText().matches("^(?=.{5,10}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$")){
            
           JOptionPane.showMessageDialog(this, "El nombre de usuario debe ser de al menos 5 "
                   + "caracteres alfanuméricos \ny puede incluir los caracteres especiales \"_\" o \".\".", 
                   "ERROR", JOptionPane.PLAIN_MESSAGE);
           tfNombreUsuario.setText("");
           tfContraseña.setText("");
           errorUsuario = true;
           
        //Mensaje para que no esté en blanco y validación para que no contenga espacios
        }else if(tfContraseña.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Por favor introduzca una contraseña.", 
                    "ERROR", JOptionPane.PLAIN_MESSAGE);
            errorUsuario = true;
        }else if(tfContraseña.getText().matches("\\s+")){
            JOptionPane.showMessageDialog(this, "La contraseña que ingresaste es incorrecta."
                    + "\nVuelve a intentarlo", "ERROR", JOptionPane.PLAIN_MESSAGE);
            tfContraseña.setText("");
            errorUsuario = true;
        }
        
        if(!errorUsuario && !errorFormulario){
           try {
                con = DriverManager.getConnection(linkbd, "root", "");
                Statement stmt = con.createStatement();
                stmt.executeUpdate("INSERT INTO Recepcionistas VALUES ('"+tfNombreUsuario.getText()+"','"+tfContraseña.getText()+"','"+tfNombre.getText()+"','"+tfApellido.getText()+"')");
                JOptionPane.showMessageDialog(null, "Registro exitoso");
                tfApellido.setText("");
                tfContraseña.setText("");
                tfNombre.setText("");
                tfNombreUsuario.setText("");
            } 
            catch (SQLException ex) {
                Logger.getLogger(PantallaRegistrarRecepcionista.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error. Intente de nuevo.");
            }
        }
        
        
            
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        MainWindow.startTime = System.currentTimeMillis();
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
