/*VERSION DE WINDOWS CRUDS COMPLETOS*/

package vista;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author pedrohdez
 */
public class PantallaCrearTutor extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCrearTutor
     */
     Connection con;
     Statement stmt;
     
     String Teléfonos[];
     File fotoTutor;
     String NombreDeFoto;
     boolean error = false;
     CamConRec camara;
     String linkbd = "jdbc:mysql://localhost:3306/VISTA?useTimezone=true&serverTimezone=UTC";
     
    public PantallaCrearTutor() {
        setSize(1000,800);
        setLocation(0,-25);
        initComponents();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaRegistrarNiño.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void IniciarPantalla(){
        //SE LIMPIAN TODOS LOS TEXT FIELDS
        tfNombres.setText("");
        tfApellidoPaterno.setText("");
        tfApellidoMaterno.setText("");
        tfTeléfono.setText("");
        lblFoto.setIcon(null);
        lblFoto.setText("SIN FOTO");
        fotoTutor = null;
        camara = new CamConRec();
        
        //SE EXTRAEN TODOS LOS TELÉFONOS DE LA BD PARA QUE AL MOMENTO DE AJUSTAR LA INFORMACIÓN NO SE REPITAN LOS TUTORES/AUTORIZADOS
        try {
            con = DriverManager.getConnection(linkbd, "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs, rs2;
            rs = stmt.executeQuery("SELECT COUNT(*) FROM Tutores");
            rs.first();
            
            Teléfonos = new String[Integer.parseInt(rs.getObject(1).toString())];
            
            rs2 = stmt.executeQuery("SELECT Telefono FROM Tutores");
            rs2.first();
            
            for(int i = 0; i < Teléfonos.length ; i++){
                Teléfonos[i] = rs2.getObject(1).toString();
                rs2.next();
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PantallaActualizarNiño.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        lblTeléfono = new javax.swing.JLabel();
        tfNombres = new javax.swing.JTextField();
        tfApellidoPaterno = new javax.swing.JTextField();
        tfApellidoMaterno = new javax.swing.JTextField();
        tfTeléfono = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        bTomarFoto = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombres.setText("Nombres:");
        getContentPane().add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblApellidoPaterno.setText("Apellido paterno:");
        getContentPane().add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        lblApellidoMaterno.setText("Apellido materno:");
        getContentPane().add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, -1));

        lblTeléfono.setText("Teléfono:");
        getContentPane().add(lblTeléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));
        getContentPane().add(tfNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 67, 145, -1));
        getContentPane().add(tfApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 104, 145, -1));
        getContentPane().add(tfApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 141, 142, -1));
        getContentPane().add(tfTeléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 178, 142, -1));

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 67, 260, 260));

        bTomarFoto.setText("Tomar foto");
        bTomarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTomarFotoActionPerformed(evt);
            }
        });
        getContentPane().add(bTomarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 333, -1, -1));

        bGuardar.setText("Guardar cambios");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 389, -1, -1));

        bActualizar.setText("Actualizar foto");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 333, -1, -1));

        jLabel1.setText("Crear Tutor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        
         for (String Teléfono : Teléfonos) {
             if ( tfTeléfono.getText().equals(Teléfono) ) {
                 JOptionPane.showMessageDialog(null, "El tutor con teléfono "+tfTeléfono.getText()+" ya existe", "ERROR", 1);
                 error = true;
                 break;
             }
         }
        
        if(tfNombres.getText().equals("") || tfApellidoPaterno.getText().equals("") || tfApellidoMaterno.getText().equals("") ||
           tfTeléfono.getText().equals("")){
            JOptionPane.showMessageDialog(null, "La información es incompleta. Revise e inténtelo de nuevo", "ERROR", 1);
            error = true;
            
        }
        
        if(!error){
             //Se introduce al niño a la base de datos
                try {
                    con = DriverManager.getConnection(linkbd, "root", "");
                    stmt = con.createStatement();
                    stmt.executeUpdate("INSERT INTO Tutores VALUES ('"+tfTeléfono.getText()+"','"+tfNombres.getText()+"','"+tfApellidoPaterno.getText()+"','"+
                            tfApellidoMaterno.getText()+"','" +(fotoTutor == null ? "No" : "Fotos Tutores/"+fotoTutor.getName())+"','null', 'Tutor')");
                } 
                catch (SQLException ex) {
                    Logger.getLogger(PantallaRegistrarNiño.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error en el registro del niño.\nIntente de nuevo.");
                }
                
                JOptionPane.showMessageDialog(null, "Se ha creado al tutor");
                dispose();
        }
        else error = false;
       
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bTomarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTomarFotoActionPerformed
        
        if(tfNombres.getText().equals("") || tfApellidoPaterno.getText().equals("")|| tfApellidoMaterno.getText().equals("") ||
              tfTeléfono.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Primero rellene el formulario del tutor", "ERROR", 1);
        }
        else{
            NombreDeFoto = "Fotos Tutores/tutor"+tfTeléfono.getText();
            JOptionPane.showMessageDialog(null, "Asegúrese de tomar la foto correctamente(Intento único)\n"
                    + "Guarde la imagen con el mismo nombre y teléfono asignados al tutor", "ADVERTENCIA", 1);
            camara.soloFoto = 0;
            camara.IniciaCamaraPro("tutor"+tfTeléfono.getText(), "Fotos Tutores");
        }
           
    }//GEN-LAST:event_bTomarFotoActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        fotoTutor = new File("Fotos Tutores/tutor"+tfTeléfono.getText()+".jpg");
        Image foto = getToolkit().getImage(fotoTutor.getAbsolutePath());
        foto = foto.getScaledInstance(260, 260, 260);
        lblFoto.setIcon(new ImageIcon(foto));
    }//GEN-LAST:event_bActualizarActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        MainWindow.startTime = System.currentTimeMillis();
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCrearTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bTomarFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTeléfono;
    private javax.swing.JTextField tfApellidoMaterno;
    private javax.swing.JTextField tfApellidoPaterno;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfTeléfono;
    // End of variables declaration//GEN-END:variables
}
