/*VERSION DE WINDOWS*/

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebasvista;

/**
 *
 * @author pedrohdez
 */
public class PantallaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    PantallaRegistrarRecepcionista pantallaregistro;
    PantallaConsultarRecepcionista consultarecepcionista;
    PantallaActualizarRecepcionista actualizarecepcionista;
    PantallaEliminarRecepcionista eliminarecepcionista;
    public PantallaAdmin() {
        initComponents();
        pantallaregistro = new PantallaRegistrarRecepcionista();
        consultarecepcionista = new PantallaConsultarRecepcionista();
        actualizarecepcionista = new PantallaActualizarRecepcionista();
        eliminarecepcionista = new PantallaEliminarRecepcionista();
        
        add(consultarecepcionista);
        add(pantallaregistro);
        add(actualizarecepcionista);
        add(eliminarecepcionista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MRecepcionistas = new javax.swing.JMenu();
        MIRegistrar = new javax.swing.JMenuItem();
        MIConsultar = new javax.swing.JMenuItem();
        MIActualizar = new javax.swing.JMenuItem();
        MIEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        MRecepcionistas.setText("Recepcionistas");

        MIRegistrar.setText("Registrar");
        MIRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIRegistrarActionPerformed(evt);
            }
        });
        MRecepcionistas.add(MIRegistrar);

        MIConsultar.setText("Consultar");
        MIConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConsultarActionPerformed(evt);
            }
        });
        MRecepcionistas.add(MIConsultar);

        MIActualizar.setText("Actualizar");
        MIActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIActualizarActionPerformed(evt);
            }
        });
        MRecepcionistas.add(MIActualizar);

        MIEliminar.setText("Eliminar");
        MIEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIEliminarActionPerformed(evt);
            }
        });
        MRecepcionistas.add(MIEliminar);

        jMenuBar1.add(MRecepcionistas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegistrarActionPerformed
        pantallaregistro.IniciarVentana();
        pantallaregistro.setVisible(true);
        eliminarecepcionista.setVisible(false);
        actualizarecepcionista.setVisible(false);
        consultarecepcionista.setVisible(false);
        consultarecepcionista.borraTabla();
    }//GEN-LAST:event_MIRegistrarActionPerformed

    private void MIConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConsultarActionPerformed
        consultarecepcionista.setVisible(true);
        eliminarecepcionista.setVisible(false);
        actualizarecepcionista.setVisible(false);
        pantallaregistro.setVisible(false);
        consultarecepcionista.borraTabla();
        consultarecepcionista.IniciarVentana();
    }//GEN-LAST:event_MIConsultarActionPerformed

    private void MIActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIActualizarActionPerformed
        actualizarecepcionista.IniciarVentana();
        eliminarecepcionista.setVisible(false);
        pantallaregistro.setVisible(false);
        actualizarecepcionista.setVisible(true);
        consultarecepcionista.setVisible(false);
    }//GEN-LAST:event_MIActualizarActionPerformed

    private void MIEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIEliminarActionPerformed
        eliminarecepcionista.IniciarVentana();
        eliminarecepcionista.setVisible(true);
        pantallaregistro.setVisible(false);
        actualizarecepcionista.setVisible(false);
        consultarecepcionista.setVisible(false);
    }//GEN-LAST:event_MIEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PantallaAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIActualizar;
    private javax.swing.JMenuItem MIConsultar;
    private javax.swing.JMenuItem MIEliminar;
    private javax.swing.JMenuItem MIRegistrar;
    private javax.swing.JMenu MRecepcionistas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
