/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebasvista;

import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedrohdez
 */
public class PantallaConsultarNiño extends javax.swing.JInternalFrame {

    /**
     * Creates new form PantallaConsultarNiño
     */
    String[] id;
    String[] fotos;
    String[] nombres;
    String[] apellidosPaternos;
    String[] apellidosMaternos;
    String[] Tutores;
    String[] Autorizados;
    Connection con;
    int tamaño;
    
    public PantallaConsultarNiño() {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaConsultarNiño.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bConsultarTodo = new javax.swing.JButton();

        bConsultarTodo.setText("Consultar todo");
        bConsultarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bConsultarTodo)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bConsultarTodo)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConsultarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarTodoActionPerformed
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("ID");
        tabla.addColumn("Foto");
        tabla.addColumn("Nombres");
        tabla.addColumn("Apellido Paterno");
        tabla.addColumn("Apellido Materno");
        tabla.addColumn("Tutor");
        tabla.addColumn("Autorizados");
        
        //NÚMERO DE NIÑOS EN LA BASE DE DATOS
         try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/VISTA", "root", "");    
            Statement stmt = con.createStatement();
            ResultSet rs, rs2;
            rs = stmt.executeQuery("SELECT count(*) FROM Ninos"); //Tamaño de los niños
            rs.first();
            rs.getString(1);
            tamaño = Integer.valueOf(rs.getString(1));
            
            //Arreglo de fotos
            fotos = new String[tamaño];
            rs2 = stmt.executeQuery("SELECT Foto FROM Ninos");
            rs2.first();
            for(int i = 0; i < tamaño ; i++){
                fotos[i] = rs2.getString(1);
                rs2.next();
                
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(PantallaConsultarNiño.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error. Intente de nuevo.");
        }
       for(int i = 0 ; i < tamaño ; i++){
           System.out.println(fotos[i]);
       }
       id = new String[tamaño];
       nombres = new String[tamaño];
       apellidosPaternos = new String[tamaño];
       apellidosMaternos = new String[tamaño];
       Tutores = new String[tamaño];
       Autorizados = new String[tamaño];
        
         
        
        
    }//GEN-LAST:event_bConsultarTodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsultarTodo;
    // End of variables declaration//GEN-END:variables
}
