
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fernandadominguez
 */
public class LogWindow extends javax.swing.JInternalFrame {
    Connection con;
    public String username;
    public String password;
    
    /**
     * Creates new form LogWindow
     */
    public LogWindow() {
        initComponents();
        setBackground(Color.lightGray);
        setSize(600,500);

    }
    
    public void Log(){
        username = tfUsername.getText();
        password = new String(pfPassword.getPassword());
        
        //lmao esta madre
        if(!username.contains("^(?=.{7,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$")){
           JOptionPane.showMessageDialog(null, "Error. Rellene los dos campos e inténtelo de nuevo.");
        }
        JOptionPane.showMessageDialog(this, "Lol, imagine like login in to use this software", "Looogin!", 
                             JOptionPane.PLAIN_MESSAGE);
        
        //System.out.println("user: " + username + " pass: " + password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VISTA");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre de Usuario: ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAlignmentX(1.0F);
        jLabel2.setAlignmentY(1.0F);
        getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
